packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - "esbuild"
allowBuilds:
  "@firebase/util": true
  "esbuild": true
  "protobufjs": true
  "re2": true
minimumReleaseAgeExclude:
  - fastify@5.11.0
